### ISSUE TITLE
OSX Install failed

### ISSUE THREAD

**Issue by jmoleiro** [fuse-x/studio#3]
Hello, i'm trying to install on Mojave (10.14.5 [18F132]) and when i run the package i get an "Instalation failed" error without further explanation. Trying to run the PKG using the installer command on the console i get the same result

```
$ sudo installer -pkg fuse-x-2.0.0-beta.2-mac.pkg -target / -allowUntrusted -verboseR 
installer: Package name is fuse X
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing fuse X…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%47.099088
installer:PHASE:Moving items into place…
installer:%84.916384
installer:PHASE:Running package scripts…
installer:%86.737891
installer:PHASE:Running package scripts…
installer:%86.866248
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
```

Any ideas?

Thanks

J

**Comment by mortend** [comment]
Hello, thanks for testing.

Another user reported a similar issue. The solution for him was to make sure destination directories are writable.

```
sudo chown -R "$(whoami)" /usr/local/bin
sudo chown -R "$(whoami)" /usr/local/lib
```

Errors from the install-script are logged to this file.

```
cat /tmp/install-fuse.err
```

Hope this helps.

**Comment by mortend** [comment]
Hopefully this issue is fixed by [v2.0.0-beta.3](https://github.com/fuse-x/studio/releases/tag/v2.0.0-beta.3).

**Comment by mdings** [comment]
Same issue here. No luck with setting the permissions for me unfortunately.

**Comment by jmoleiro** [comment]
HI! I've tried the permission settings and the new version (2.0.0 b3). But no luck. That's the content of the /tmp/install-fuse.err

```
npm WARN using --force I sure hope you know what you are doing.
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/jmoleiro/.dotnet-run/.bin/mono ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm WARN using --force I sure hope you know what you are doing.
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/jmoleiro/.dotnet-run/.bin/mono ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm WARN using --force I sure hope you know what you are doing.
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/jmoleiro/.dotnet-run/.bin/mono ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

I have mono installed, but via VS Mac. Could this be the problem behind the process not finding the mono executable at "/Users/jmoleiro/.dotnet-run/.bin/mono"?

**Comment by mortend** [comment]
Hi!

It is recommended to install the [latest stable version of Mono](https://www.mono-project.com/download/stable/#download-mac) and the [latest LTS version of Node.js](https://nodejs.org/en/download/).

Because you said you installed via VS Mac it sounds like you're already using this version of Mono. Hmm...

The [dotnet-run](https://www.npmjs.com/package/dotnet-run) package is supposed to detect a compatible Mono installation and create a symlink at `/Users/$USER/.dotnet-run/.bin/mono`, and it looks like this didn't work for you. Can you please try installing only `dotnet-run` and check what the log says about it?

```
npm install -g dotnet-run
```

Thank you!

**Comment by mdings** [comment]
Didn't work for me after updating the dependencies unfortunately.
Thanks for looking into this @mortend !

**Comment by mortend** [comment]
The latest version addresses the dotnet-run issue. https://github.com/fuse-x/studio/releases/tag/v2.0.0-beta.4

**Comment by mdings** [comment]
I got this working now successfully 💯

**Comment by mdings** [comment]
I had to buy a new iMac for it though but it was totally worth it 😀
